export const ModalName = {
  sideBar: 'sideBar',
  addScheduleMemo: 'addScheduleMemo',
  editScheduleMemo: 'editScheduleMemo',
  addImageMemo: 'addImageMemo',
  detailTextMemo: 'detailTextMemo',
  detailImageMemo: 'detailImageMemo',
  detailImageMemoExpand: 'detailImageMemoExpand',
  detailScheduleMemo: 'detailScheduleMemo',
  memoCollection: 'memoCollection',
  detailImageMemoCollection: 'detailImageMemoCollection',
  detailScheduleMemoCollection: 'detailScheduleMemoCollection',
  addCategory: 'addCategory',
  editCategory: 'editCategory',
  searchMemo: 'searchMemo',
  editMemoCategory: 'editMemoCategory',
  withdrawUser: 'withdrawUser',
};
